### ISSUE TITLE
Version 2.5.0 was deleted from apt repository.

### ISSUE THREAD

**Issue by themoah** [maxmind/geoipupdate-legacy#106]
Guys,

This is not serious. 
We are paying customer who uses GeoIP DB. You just deleted version 2.5.0 (`2.5.0-0+maxmind1~xenial`) from APT repository and only left there 3.0.0 (`3.0.0-0+maxmind1~xenial`) without updating before it happens.
It just broke things.. 
Please return it ASAP.

**Comment by oschwald** [comment]
We released 3.0.0, which is available from the PPA. Launchpad automatically removes old versions when a new version is released. This is out of our control. What specifically broke?

**Comment by themoah** [comment]
@oschwald 3.0.0 has breaking changes (configuration - structure of file), thus installing `geoipupdate` brings us version that won't work. 

So if you say, that release of newer version deletes older one and it is

>  This is out of our control

Please tell your customers that you are planning to roll out new version with some time ahead, so we could adopt to the changes.

**Comment by oschwald** [comment]
How is the configuration breaking for you in particular?

**Comment by themoah** [comment]
@oschwald scenario:

1. we spin up new instance (not manually, via code), it installs `geoipupdate` with pre-configured by us configuration.
2. we run `geoipupdate` for the first time to bring latest (fails) and add it to cron (will fail). 
3. our applications rely on this GeoIP DB. (we are paying customer).

**Comment by oschwald** [comment]
@themoah, thanks. I am still not completely clear on how it is breaking, but we did release 3.0.1 that fixes an issue with the exit code when there are no updates available. Would you be able to try this?

If not, could you run `geoipupdate` with the `-v` flag and provide the output?

Thanks!

**Comment by oschwald** [comment]
If you provide the output from `-v`, please be sure to _not_ include your license key, which may appear in the output.

**Comment by themoah** [comment]
@oschwald 
`/usr/bin/geoipupdate -v
geoipupdate 3.0.1
Opened License file /etc/GeoIP.conf
UserId XXXXX
LicenseKey XXXXXXX
Insert edition_id 106
Insert edition_id 121
Insert edition_id 133
Insert edition_id GeoIP2-City
Insert edition_id GeoIP2-Country
Insert edition_id GeoIP2-ISP
Read in license key /etc/GeoIP.conf
Number of edition IDs 6
/usr/share/GeoIP is not writable: Success`

Looks like 3.0.1 fixed it. 
thanks !
