### ISSUE TITLE
Problem installing.

### ISSUE THREAD

**Issue by adammenges** [maxmind/geoipupdate-legacy#11]
``` bash
deploy@ip---:~/code/libs$ git clone https://github.com/maxmind/geoipupdate
Cloning into 'geoipupdate'...
deploy@ip---:~/code/libs$ cd geoipupdate/
deploy@ip---:~/code/libs/geoipupdate$ ./bootstrap 
./bootstrap: 5: ./bootstrap: autoreconf: not found
```

**Comment by oschwald** [comment]
`autoreconf` is part of `autoconf`, which you will need to install if you want to build this from a checkout. However, if you just want to install the latest version, I would recommend downloading `geoipupdate-2.0.1.tar.gz` from the [releases page](https://github.com/maxmind/geoipupdate/releases). This version is already bootstrapped.

**Comment by adammenges** [comment]
Ah, much easier, cheers.
