### ISSUE TITLE
Question about availability

### ISSUE THREAD

**Issue by akordzik** [maxmind/geoipupdate-legacy#113]
Hi,

I have a question about availability during the auto update of GeoLite2 database. Is there any downtime during the update itself?

Thanks!

**Comment by oschwald** [comment]
I am not 100% sure I understand the question, but the database is replaced atomically. If you have an open database, it should not be affected by the update. However, your application may need to close the database and reload it to see the new version. I would suggest that you email [support@maxmind.com](mailto:support@maxmind.com) for more assistance.
