### ISSUE TITLE
ASN database not installing/updating

### ISSUE THREAD

**Issue by ddmud** [maxmind/geoipupdate-legacy#114]
I am trying to install the ASN database listed here: https://dev.maxmind.com/geoip/geoip2/geolite2/

I have the following in my GeoIP.conf file:

```
AccountID 0
LicenseKey 000000000000
EditionIDs GeoLite2-City GeoLite2-Country GeoLite2-ASN
```

I then run `sudo /usr/bin/geoipupdate` but the ASN database does not get installed nor do i get any errors. The City and Country databases install fine. Am I missing something?

**Comment by horgh** [comment]
I'll close this in favour of https://github.com/maxmind/geoipupdate/issues/16.
