### ISSUE TITLE
MD5 authentication breaks behind NAT

### ISSUE THREAD

**Issue by tmm1** [maxmind/geoipupdate-legacy#12]
Since updates.maxmind.com does not support HTTP/1.1, curl is unable to use http keepalive and re-use a single TCP connection.

This means a new TCP connection per http request, which breaks the md5 authentication since source ips can change between connections when behind a NAT.

**Comment by oschwald** [comment]
Thanks for letting us know. We will look into this. It sounds like the easiest fix may be to update the daemon to support HTTP/1.1.

**Comment by oschwald** [comment]
We believe this has been fixed. Our geoipupdate server should now support HTTP/1.1 with Keep-Alive. Would you be able to test it to confirm that it works in your environment?
