### ISSUE TITLE
apache restart needed after update

### ISSUE THREAD

**Issue by dirkgomez** [maxmind/geoipupdate-legacy#15]
Thanks for this niece little tool, saves a fair bit of time.

I have got one question that I don't see addressed anyway: do I have to restart Apache after having updated the GeoIP database - in my case it's the country one (#106)

**Comment by oschwald** [comment]
This would depend on how you are accessing the database. If you are using PHP or Perl, your application will need to close and reopen the database. If you are using `mod_maxminddb`, you will need to reload Apache (sending a HUP signal is likely enough).
