### ISSUE TITLE
Pre-built package for Ubuntu?

### ISSUE THREAD

**Issue by mjwillson** [maxmind/geoipupdate-legacy#16]
Hello

Is an up-to-date version of this tool available anywhere as an Ubuntu package? If not, any chance you guys could create binary packages for Ubuntu and release in a PPA? Having to configure and build it on the server in order to install isn't exactly ideal as it requires having a build toolchain installed, and it also makes it fiddly to update it to the latest version when new releases are made.

Previously I've been able to use a `geoipupdate` installed via an existing Ubuntu package (geoip-bin), but this doesn't seem to work any more for me after signing up for the GeoIP2 City, I'm guessing they're no longer maintained by you guys?

Cheers
-Matt

**Comment by oschwald** [comment]
Versions of geoipupdate prior to 2.0, like the one in Ubuntu, don't support the GeoIP2 databases. There has been some talk of doing a PPA, but I'll bring it up again. Thanks for your feedback!

**Comment by mjwillson** [comment]
OK, cheers for the info. Installing via a PPA would make this a much smoother process :)

**Comment by oschwald** [comment]
We have a PPA now at https://launchpad.net/~maxmind/+archive/ubuntu/ppa/

**Comment by mjwillson** [comment]
Awesome, thanks!

On Tue, Nov 11, 2014 at 11:40 PM, Gregory Oschwald <notifications@github.com
