### ISSUE TITLE
Unadvertised build dependencies

### ISSUE THREAD

**Issue by mjwillson** [maxmind/geoipupdate-legacy#17]
Kinda relevant to the "can we have binary packages for Ubuntu please?" ticket, but if we need to build this package ourselves you might want to advertise the build dependencies :)

From what I can see, on Ubuntu you need at least `build-essentials`, one of `libcurl4-{gnutls,openssl,nss}-dev`, and `zlib1g-dev`, although there may be more.

**Comment by oschwald** [comment]
Thanks. We should include those.
