### ISSUE TITLE
Protocol docs in `GeoIP.conf` are confusing

### ISSUE THREAD

**Issue by chicks-net** [maxmind/geoipupdate-legacy#23]
In `GeoIP.conf` https://github.com/maxmind/geoipupdate/blob/master/conf/GeoIP.conf.default#L19  it says:

```
# The desired protocol either "https" (default) or "https".     
```

It is saying **https** twice.  So it is not clear whether `http` or `https` is actually the default.  Presumably one of those should not include the _s_ but even reading the source code does not make it clear which _s_ should be removed to me.

**Comment by oschwald** [comment]
Thanks!

**Comment by chicks-net** [comment]
Awesome speed!  :rocket:

Where does the default of https come from?

**Comment by oschwald** [comment]
[Here](https://github.com/maxmind/geoipupdate/blob/e6d4b053903ac04650f14f0cb0396b1a27ae44bd/bin/geoipupdate_s.c#L13). You can verify that it is set correctly by running it with the `-v` option.

**Comment by chicks-net** [comment]
Awesome @oschwald thanks
