### ISSUE TITLE
node.js version of geolite-mirror-simple.pl

### ISSUE THREAD

**Issue by msimerson** [maxmind/geoipupdate-legacy#24]
I couldn't find a better place to post this issue. When using the perl version of GeoIP, there's the handy [geolite-mirror-simple.pl](http://cpansearch.perl.org/src/MAXMIND/Geo-IP-1.45/example/geolite-mirror-simple.pl) script that keeps the database files up-to-date in a bandwidth efficient way. Good for me, and good for your server.

Now I use node.js and a couple different GeoIP modules and needed something to keep the local databases updated, so I made a node.js port of the perl script called [maxmind-geolite-mirror](https://www.npmjs.com/package/maxmind-geolite-mirror). It's on npm now, and you're welcome to link to, share, or even take ownership of it. 

A direct link to the [script](https://github.com/msimerson/maxmind-geolite-mirror/blob/master/bin/maxmind-geolite-mirror). It uses only node.js built-ins so there's no dependencies.

**Comment by oschwald** [comment]
Thanks for the link!
