### ISSUE TITLE
Tarball does not contain LICENSE file

### ISSUE THREAD

**Issue by pprindeville** [maxmind/geoipupdate-legacy#25]
At least the geoipupdate-2.1.0.tar.gz file doesn't:

$ tar ztvf ../geoipupdate-2.1.0.tar.gz | sort 
drwxrwxr-x 1000/1000         0 2014-11-06 14:50 geoipupdate-2.1.0/
drwxrwxr-x 1000/1000         0 2014-11-06 14:50 geoipupdate-2.1.0/bin/
drwxrwxr-x 1000/1000         0 2014-11-06 14:50 geoipupdate-2.1.0/conf/
drwxrwxr-x 1000/1000         0 2014-11-06 14:50 geoipupdate-2.1.0/man/
-rw-r--r-- 1000/1000      1063 2014-02-07 08:09 geoipupdate-2.1.0/bin/product_s.c
-rw-r--r-- 1000/1000      1204 2014-02-07 08:09 geoipupdate-2.1.0/conf/GeoIP.conf.default
-rw-r--r-- 1000/1000      1208 2014-05-02 09:28 geoipupdate-2.1.0/README.md
-rw-r--r-- 1000/1000      1426 2014-11-06 14:48 geoipupdate-2.1.0/configure.ac
-rw-r--r-- 1000/1000       152 2014-05-02 09:13 geoipupdate-2.1.0/Makefile.am
-rw-r--r-- 1000/1000      1716 2014-06-02 10:32 geoipupdate-2.1.0/man/GeoIP.conf.5.in
-rw-r--r-- 1000/1000    283686 2014-11-06 14:49 geoipupdate-2.1.0/ltmain.sh
-rw-r--r-- 1000/1000       327 2014-05-02 09:17 geoipupdate-2.1.0/bin/Makefile.am
-rw-r--r-- 1000/1000       561 2014-05-02 09:19 geoipupdate-2.1.0/conf/Makefile.am
-rw-r--r-- 1000/1000       781 2014-05-02 09:19 geoipupdate-2.1.0/man/Makefile.am
-rw-rw-r-- 1000/1000      1264 2014-10-21 08:06 geoipupdate-2.1.0/bin/geoipupdate.h
-rw-rw-r-- 1000/1000      1265 2014-10-21 08:06 geoipupdate-2.1.0/bin/md5.h
-rw-rw-r-- 1000/1000     14565 2014-11-06 14:49 geoipupdate-2.1.0/conf/Makefile.in
-rw-rw-r-- 1000/1000      1487 2014-11-06 14:47 geoipupdate-2.1.0/ChangeLog.md
-rw-rw-r-- 1000/1000     17267 2014-11-06 14:49 geoipupdate-2.1.0/man/Makefile.in
-rw-rw-r-- 1000/1000     17813 2014-11-06 14:48 geoipupdate-2.1.0/bin/geoipupdate.c
-rw-rw-r-- 1000/1000     18211 2014-10-21 08:06 geoipupdate-2.1.0/bin/base64.c
-rw-rw-r-- 1000/1000     19655 2014-11-06 14:49 geoipupdate-2.1.0/bin/Makefile.in
-rw-rw-r-- 1000/1000      2094 2014-10-21 08:06 geoipupdate-2.1.0/bin/base64.h
-rw-rw-r-- 1000/1000      2098 2014-04-14 16:11 geoipupdate-2.1.0/man/geoipupdate.1.in
-rw-rw-r-- 1000/1000     24444 2014-11-06 14:49 geoipupdate-2.1.0/Makefile.in
-rw-rw-r-- 1000/1000    351030 2014-11-06 14:49 geoipupdate-2.1.0/aclocal.m4
-rw-rw-r-- 1000/1000      3631 2014-10-21 08:06 geoipupdate-2.1.0/bin/types.h
-rw-rw-r-- 1000/1000      8258 2014-07-22 09:51 geoipupdate-2.1.0/bin/geoipupdate-pureperl.pl
-rw-rw-r-- 1000/1000      9731 2014-10-21 08:06 geoipupdate-2.1.0/bin/md5.c
-rw-rw-r-- 1000/1000       987 2014-10-21 08:06 geoipupdate-2.1.0/bin/geoipupdate_s.c
-rwxrwxr-x 1000/1000    432601 2014-11-06 14:49 geoipupdate-2.1.0/configure
-rwxr-xr-x 1000/1000     13997 2014-11-06 14:49 geoipupdate-2.1.0/install-sh
-rwxr-xr-x 1000/1000     23566 2014-11-06 14:49 geoipupdate-2.1.0/depcomp
-rwxr-xr-x 1000/1000     35837 2014-11-06 14:49 geoipupdate-2.1.0/config.sub
-rwxr-xr-x 1000/1000     42856 2014-11-06 14:49 geoipupdate-2.1.0/config.guess
-rwxr-xr-x 1000/1000       429 2014-02-07 08:09 geoipupdate-2.1.0/bootstrap
-rwxr-xr-x 1000/1000      6872 2014-11-06 14:49 geoipupdate-2.1.0/missing
-rwxr-xr-x 1000/1000      7333 2014-11-06 14:49 geoipupdate-2.1.0/compile

Is this a known issue?  It's required for distro packaging.

**Comment by pprindeville** [comment]
Also recommend amending the Makefile.in/.am to install LICENSE file into $(docdir)/

**Comment by pprindeville** [comment]
One other suggestion: also install GeoIP.conf.default into $(docdir) and not into $(sysconfdir).

**Comment by oschwald** [comment]
Could you open a separate issue for the install paths? We should clean that up, but it is separate from and secondary to the license being missing.
