### ISSUE TITLE
DatabaseDirectory

### ISSUE THREAD

**Issue by stuintrepica** [maxmind/geoipupdate-legacy#28]
I can't find a mention other than in the source code for the DatabaseDirectory.

We access the database from a rails project where the database is located relative to it.

Is it correct that I can just put a full path in the conf file for DatabaseDirectory?

**Comment by oschwald** [comment]
Yes. This is also [in the man page](https://github.com/maxmind/geoipupdate/blob/15c12e691bdbc670c06af613ce742c5e92319b83/man/GeoIP.conf.5.in#L33), but we should add it to the sample conf file as well.
