### ISSUE TITLE
/usr/local/share/GeoIP does not exist

### ISSUE THREAD

**Issue by antokara** [maxmind/geoipupdate-legacy#29]
on CentOS 6.6

downloaded and extracted the latest bootstrapped source, then

```
#./configure
#make
#make install
```

execute 

```
$/usr/local/bin/geoipupdate
```

but prompts

```
/usr/local/share/GeoIP does not exist
```

a simple 

```
$mkdir /usr/local/share/GeoIP
```

fixes the problem, perhaps it can be automatically created to avoid such issues?
thanks.

**Comment by b3n3d1k7** [comment]
Had the same problem on Debian 8.0.

**Comment by oschwald** [comment]
The directory to use can be set in the conf file or at run time, but I agree that we should create the default directory.

**Comment by dugwood** [comment]
This is not an issue to me: you have to know where to put it. Default to `/usr/local/share/GeoIP/` is an obvious choice, it can't be `/usr/share/GeoIP/` as Debian package `geoip-database` writes to it.

And libgeoip-dev uses `/usr/share/GeoIP/` as a default. So if you don't know where the files are, you can't see an issue. Creating a default directory will prevent the error, but then you'll ask yourself why libgeoip-dev doesn't find updates...

Setting all variables in your configuration file is the right way to go. I **do** want the files to go to `/usr/share/GeoIP/`, so I write so in the configuration file.

Question is where the conf file was written... oh, it's in `/usr/local/etc/`, I will change the `prefix` (edit: it's `--sysconfdir=DIR`)
