### ISSUE TITLE
Use of "getline" breaks compilation on Mac OS X 10.6

### ISSUE THREAD

**Issue by jacknagel** [maxmind/geoipupdate-legacy#3]
OS X 10.6 and older do not provide the "getline" function which is used in geoipupdate.c.

The usual approach is to detect this at configure time and provide some kind of fallback implementation.

I don't use this software myself, but a Homebrew user on 10.6 reported the issue: https://github.com/Homebrew/homebrew/issues/25865

**Comment by borisz** [comment]
If you have the opportunity, please check if the workaround in [bz/workaround-missing-getline](https://github.com/maxmind/geoipupdate/tree/bz/workaround-missing-getline) works.

**Comment by sidney** [comment]
I found this issue after getting the build failure using homebrew on Mac OS 10.6.8. The branch works for me. For other homebrew users who find this page from the downstream bug report, here are the exact steps to try this patch:

I used 
    brew edit geoipupdate
to edit the recipe, adding the branch option to the url line in the head function to make it say
    url 'https://github.com/maxmind/geoipupdate.git', :branch => 'bz/workaround-missing-getline'
and then did
    brew install --HEAD geoipupdate

**Comment by oschwald** [comment]
Thanks. This was fixed by #4.
