### ISSUE TITLE
geoipupdate binary not available in 2.2.0-0+maxmind1~trusty

### ISSUE THREAD

**Issue by manuelfelipe** [maxmind/geoipupdate-legacy#31]
Hello, 

if using 2.1.0-0+maxmind2~trusty from ppa:maxmind/ppa I'm able to get the binaries for geoipupdate without problems in Ubuntu 14.04. Now, if using the latest package (2.2.0-0+maxmind1~trusty) I'm only getting the man page and not binaries.

**Comment by oschwald** [comment]
Gah, sorry about that. I just did a release that should fix the issue.

**Comment by manuelfelipe** [comment]
Nice. thanks. it's working now
