### ISSUE TITLE
No way to update GeoIPASNum2v6 DB?

### ISSUE THREAD

**Issue by devicenull** [maxmind/geoipupdate-legacy#35]
There does not appear to be a product definition for GeoIPASNum2v6, so this database cannot be updated

It is still listed here: http://dev.maxmind.com/geoip/legacy/geolite/

**Comment by oschwald** [comment]
It should work with the ID `517`.

**Comment by oschwald** [comment]
See [our directions](http://dev.maxmind.com/geoip/geoipupdate/#For_Free_GeoLite2_and_GeoLite_Legacy_Databases) for more information.

**Comment by devicenull** [comment]
https://updates.maxmind.com/app/update_getfilename?product_id=517 = GeoLiteASNum.dat

Where's the v6 one?

**Comment by devicenull** [comment]
This one:

http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNumv6.dat.gz

**Comment by oschwald** [comment]
Ah, you are correct. That database isn't currently supported by the web service that `geoipupdate` talks to.

**Comment by oschwald** [comment]
Closing as we have no plans to support the legacy IPv6 ASN database via geoipupdate. I would suggest switching to the GeoLite2 database.
