### ISSUE TITLE
Fails with error -21 (Sanity check database_info string failed) when attempting to update GeoIP Database

### ISSUE THREAD

**Issue by akuryan** [maxmind/geoipupdate-legacy#37]
I am using CentOs (uname: 2.6.32-042stab094.8 #1 SMP Tue Dec 16 20:36:56 MSK 2014 x86_64 x86_64 x86_64 GNU/Linux) and compiled GeoIP update from sources.
For now, I am trying to use free version of MaxMind to test this tool, but it ultimately fails with cryptic error:
[ GeoIP]$ sudo geoipupdate
MD5 Digest of installed database is fcdae7627066bce46902c0d1e331a3ed
Updating /usr/share/GeoIP/GeoIP.dat
Received Error -21 (Sanity check database_info string failed) when attempting to update GeoIP Database

I tried both with default config and config, proposed here - http://dev.maxmind.com/geoip/geoipupdate/

**Comment by oschwald** [comment]
This error message is from a 1.x version of geoipupdate. Please update to 2.2.1 and try again.

**Comment by akuryan** [comment]
I installed from sources, following instructions https://github.com/maxmind/geoipupdate#installing-from-github

**Comment by oschwald** [comment]
What is the output of `geoipupdate -V`? Might you have another version installed as well. That check and error string does not exist in geoipudpate 2.x.

**Comment by akuryan** [comment]
geoipupdate -V
Unknown option `-V'.
Usage: geoipupdate [-hv] [-f license_file] [-d custom directory]

I compiled directly from repository, following instructions. Maybe something wrong with instructions?

**Comment by oschwald** [comment]
On a 2.x version, that would return the version number. You are using an older version of geoipupdate. You likely have two in your path. You can determine which is being called by `which geoipupdate`. Assuming you used the default prefix, the one installed using the instructions should be at `/usr/local/bin/geoipupdate`.

**Comment by akuryan** [comment]
Thanks, you are right

**Comment by xoroz** [comment]
tried using it, quite useless!
just do:
url ipinfo.io/195.115.202.129
