### ISSUE TITLE
RPM packaging and distribution

### ISSUE THREAD

**Issue by marstonstudio** [maxmind/geoipupdate-legacy#40]
Request to get geoipupdate packaged for RedHat / Fedora / Amazon Linux style distributions and into the RPM repositories.

We use GeoIP2 in our Amazon Linux images, it must be installed as a standalone binary during our deployment processes. Would be great to have the latest geoipupdate as a maintained RPM package we could install through Yum instead.

Currently 1.6.5 is the latest version that is out there: http://rpm.pbone.net/index.php3?stat=3&search=GeoIP&srodzaj=3&dist[]=74

**Comment by oschwald** [comment]
You seemed to link to the libGeoIP packages. Fedora has [geoipupdate 2.2.2](http://koji.fedoraproject.org/koji/packageinfo?packageID=19898) builds.

**Comment by marstonstudio** [comment]
geoipupdate shows up in EPEL repo in Amazon Linux. I'm in business.

Thank you for the clarification.
