### ISSUE TITLE
geoipupdate not working

### ISSUE THREAD

**Issue by tetlika** [maxmind/geoipupdate-legacy#42]
hi,

we're trying to use GeoIP.x86_64, version 1.4.8-1.5.amzn1
it comes as a standard rpm package with latest Amazon Linux AMI (https://aws.amazon.com/amazon-linux-ami/)

config file looks like that:

UserId 999999
LicenseKey 000000000000
ProductIds GeoLite2-City

when trying to do geoipupdate we receive next error (see full command output):

geoipupdate -v

Opened License file /etc/GeoIP.conf
Read in license key 000000000000
number of product ids 1
Connecting to MaxMind GeoIP server
via Host or Proxy Server: api.maxmind.com:80
sending request GET /app/update_getfilename?product_id=GeoLite2-City HTTP/1.0
Host: updates.maxmind.com

database product id GeoLite2-City database file name /usr/share/GeoIP/GeoLite2-City.mmdb
/usr/share/GeoIP/GeoLite2-City.mmdb can't be opened, proceeding to download database
MD5 sum of database /usr/share/GeoIP/GeoLite2-City.mmdb is 0000000000000000000000000000000
Connecting to MaxMind GeoIP Update server
sending request GET /app/update_getipaddr HTTP/1.0
Host: updates.maxmind.com

client ip address: 52.13.23.6
md5sum of ip address and license key is 293bc8034681624265d4d6b9d917ddda
sending request GET /app/update_secure?db_md5=0000000000000000000000000000000&challenge_md5=293bc8034681624265d4d6b9d917ddda&user_id=999999&edition_id=GeoLite2-City HTTP/1.0
Host: updates.maxmind.com

Downloading gzipped GeoIP Database...
Done
Updating /usr/share/GeoIP/GeoLite2-City.mmdb
Saving gzip file to /usr/share/GeoIP/GeoLite2-City.mmdb.gz ... download data to a gz file named /usr/share/GeoIP/GeoLite2-City.mmdb.gz
Done
Uncompressing gzip file ... Done
Performing santity checks ... Database type is 1
database_info  FAIL null
Received Error -21 (Sanity check database_info string failed) when attempting to update GeoIP Database

what is wrong, and how it can be fixed?

thx

**Comment by oschwald** [comment]
You are using a 1.x version of geoipupdate, which does not support GeoIP2/GeoLite2. Please upgrade to a 2.x version.
