### ISSUE TITLE
Missing product ID for GeoLite ASN IPv6

### ISSUE THREAD

**Issue by jw35** [maxmind/geoipupdate-legacy#43]
The 'online guide' only includes ProductCodes for 5 of the 6 free Geolite legacy databases.Please, what's the ProductCode for the [free, legacy GeoLite ASN IPv6 database ](http://dev.maxmind.com/geoip/legacy/geolite/)?

**Comment by oschwald** [comment]
Unfortunately the GeoLite Legacy ASN IPv6 database is currently not available through geoipupdate.
