### ISSUE TITLE
Can't fetch GeoLite Country IPv6 Legacy

### ISSUE THREAD

**Issue by bober2000** [maxmind/geoipupdate-legacy#44]
When running geoipupdate I'm getting next output:

coral:~ # geoipupdate 
/usr/share/GeoIP/GeoIPv6.dat can't be opened, proceeding to download database
Updating /usr/share/GeoIP/GeoIPv6.dat
Received Error -21 (Sanity check database_info string failed) when attempting to update GeoIP Database
MD5 Digest of installed database is fa3e1cc9440d44ecfa5c583abe172620
/usr/share/GeoIP/GeoLiteCityv6.dat is up to date, no updates required
GeoIP Database up to date
MD5 Digest of installed database is 059b96d5bb4539e5d56e3a01038eefa9
/usr/share/GeoIP/GeoLiteCountry.dat is up to date, no updates required
GeoIP Database up to date
MD5 Digest of installed database is a2fdc5f314766bbe95710276c41ac6a7
/usr/share/GeoIP/GeoLiteCity.dat is up to date, no updates required
GeoIP Database up to date

My GeoIP.conf

coral:~ # cat /etc/GeoIP.conf
# If you purchase a subscription to the GeoIP database,
# then you will obtain a license key which you can
# use to automatically obtain updates.
# for more details, please go to
# http://www.maxmind.com/app/products
# see https://www.maxmind.com/app/license_key_login to obtain License Key,
# UserId, and available ProductIds
# Enter your license key here

LicenseKey 999999
# Enter your User ID here

UserId 000000000000
# Enter the Product ID(s) of the database(s) you would like to update
# By default 106 (MaxMind GeoIP Country) is listed below
# ProductIds 106

ProductIds GeoLite-Legacy-IPv6-Country GeoLite-Legacy-IPv6-City 506 533

**Comment by oschwald** [comment]
You appear to be using a 1.x version of `geoipupdate`. Please upgrade to the latest version.
