### ISSUE TITLE
Update release dates?

### ISSUE THREAD

**Issue by akmalabbasov** [maxmind/geoipupdate-legacy#45]
Is there a predefined dates, or periods of time when new updates are released, so we can run the `geoipupdate` the same or the day after. Currently I'm running it everyday.

**Comment by oschwald** [comment]
Please contact [support@maxmind.com](mailto:support@maxmind.com) for information about the database release schedule.

That said, `geoipupdate` will not download the full database each time. Instead it first checks if a new release is available.
