### ISSUE TITLE
./bootstrap give some issue

### ISSUE THREAD

**Issue by suranjita2016** [maxmind/geoipupdate-legacy#47]
I ran ./bootstrap and I am getting following issue.

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoconf --force
configure.ac:12: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1

**Comment by oschwald** [comment]
You need libtool to run that script, as [mentioned in the documentation](https://github.com/maxmind/geoipupdate#installing-from-github). However, most end user should download our [packaged version](https://github.com/maxmind/geoipupdate/releases), such as [geoipupdate-2.2.2.tar.gz](https://github.com/maxmind/geoipupdate/releases/download/v2.2.2/geoipupdate-2.2.2.tar.gz) that already has the configure script generated.
