### ISSUE TITLE
Unable to download GEO-108 and GEO-124 through geoipupdate

### ISSUE THREAD

**Issue by kshitijsv** [maxmind/geoipupdate-legacy#48]
Hi,

I've been trying to download GEO-108 (GeoIP Legacy Country) and GEO-124 (GeoIP Legacy ISP) through geoipupdate.
Here's what my product ids in GeoIP.conf look like : 
ProductIds 108 124
However, when I run geoipupdate, I get the following error : 
Received an unexpected HTTP status code of 404 from https://updates.maxmind.com/app/update_getfilename?product_id=108

Can you please suggest what I am missing here or if these files are not available via geoipupdate at all?

Thanks and Regards

**Comment by oschwald** [comment]
This tool is only for the binary databases. It does not support the CSV databases.

**Comment by kshitijsv** [comment]
Any suggestions/tools for auto update of the csv databases?

Thanks and Regards

**Comment by oschwald** [comment]
Unfortunately, we do not provide a tool for this. You could set up a weekly cron job to download it with curl or wget.
