### ISSUE TITLE
add-apt-repository not working

### ISSUE THREAD

**Issue by toddbruner** [maxmind/geoipupdate-legacy#53]
Ubuntu 14.04 system clean build
Behind proxy, with http_proxy and https_proxy variables set and tested.
```
/etc/apt/apt.conf 
Acquire::http::Proxy "http://proxy.foo.com:80";
Acquire::https::Proxy "https://proxy.foo.com:80";
```

Refreshed CA's
```
$ sudo -E bash
# apt-get install --reinstall ca-certificates
```
Time to add PPA
```
# add-apt-repository ppa:maxmind/ppa
Cannot add PPA: 'ppa:maxmind/ppa'.
Please check that the PPA name or format is correct.
```

I've exhausted the suggestions from various google searches on similar problems.

Also tried:
```
# add-apt-repository "deb http://ppa.launchpad.net/maxmind/ppa/ubuntu trusty main"
apt-get update
...
Reading package lists... Done
W: GPG error: http://ppa.launchpad.net trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY DE1997DCDE742AFA
```

**Comment by oschwald** [comment]
This sounds like a problem with your proxy configuration. I'd suggest asking on http://askubuntu.com/. We just use a standard Ubuntu PPA provided by Launchpad: https://launchpad.net/~maxmind/+archive/ubuntu/ppa
