### ISSUE TITLE
man page should document all config file options

### ISSUE THREAD

**Issue by horgh** [maxmind/geoipupdate-legacy#64]
It's missing the recent new option `LockFile`. See `man/GeoIP.conf.5.in`.

**Comment by ZaneHintzman** [comment]
Just to be clear, is this the man page you're talking about?:

http://manpages.ubuntu.com/manpages/zesty/en/man1/geoipupdate.1.html

I'm new to this tool, and don't know if there's accurate documentation somewhere. I installed version 2.3.1 on one machine and 2.4.0 on another. For version 2.3.1, it appears to use the config file in /usr/local/etc, whereas in version 2.4.0, it uses the one in /etc. Also, for version 2.3.1, the default database directory is /usr/local/share/GeoIP, but for version 2.4.0 it seems to use /usr/share/GeoIP, even though the default config file still says it should default to /usr/local/share/GeoIP. Am I understanding this correctly?

**Comment by horgh** [comment]
Hi @ZaneHintzman 

Yes, your link is an example of the generated version of the man page. The source to generate it is the file I mentioned in this repository, `man/GeoIP.conf.5.in`.

The directories/paths used by `geoipupdate` and the man page depend on flags you provide to `./configure`. They can be different depending on how it is built and packaged. The Ubuntu package uses directories different from the defaults you get if you build directly from the repository. The defaults did not change between 2.3.1.

You should be able to treat the man page on your system as accurate, but as I say, the paths can vary depending on how you install the package.
