### ISSUE TITLE
curl_easy_perform() failed: SSL connect error

### ISSUE THREAD

**Issue by mash7** [maxmind/geoipupdate-legacy#66]
Hi,
I am getting the following error:

* About to connect() to updates.maxmind.com port 443 (#0)
*   Trying 108.168.254.117... * connected
* Connected to updates.maxmind.com (108.168.254.117) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS error -5961
* Closing connection #0
* SSL connect error
curl_easy_perform() failed: SSL connect error
Connect to https://updates.maxmind.com/app/update_getfilename?product_id=GeoIP2-City

I am using the latest version from the GIT on centos. 
Please let me know how to fix it. Thanks

**Comment by oschwald** [comment]
What version of libcurl are you using and what version of CentOS? If I had to guess, I would guess it is related to https://github.com/curl/curl/issues/700

**Comment by oschwald** [comment]
I am closing this due to lack of follow-up information and given that it appears the likely culprit has been fixed in CentOS already.
