### ISSUE TITLE
On RHEL 6.9 Perl dependency should be IO::Uncompress::Gunzip instead of PerlIO::gzip

### ISSUE THREAD

**Issue by zielot** [maxmind/geoipupdate-legacy#67]
We would like to use "geoipupdate-2.4.0/bin/geoipupdate-pureperl.pl" for automatic updates
The Perl script depends on PerlIO::gzip and when I run on RHEL 6.9 fails with:
`Can't locate PerlIO/gzip.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/local/bin/geoipupdate.pl line 52.
BEGIN failed--compilation aborted at /usr/local/bin/geoipupdate.pl line 52.`
However, the gzip module is installed:
`$ find /usr/ -iname gzip.pm`
`/usr/lib64/perl5/IO/Compress/Gzip.pm`
and
`$ sudo yum whatprovides 'perl(IO::Uncompress::Gunzip)'`
`Loaded plugins: product-id, rhnplugin, search-disabled-repos, security, subscription-manager`
`This system is receiving updates from RHN Classic or RHN Satellite.`
`rhel-x86_64-server-6 `
...
`perl-IO-Compress-Zlib-2.021-144.el6.x86_64 : Perl interface to allow reading and writing of gzip and zip data`
`Repo        : installed`
`Matched from:`
`Other       : Provides-match: perl(IO::Uncompress::Gunzip)`
Changing the use statement in the Perl script from PerlIO::gzip to use IO::Uncompress::Gunzip;
appears to fix the issue.

**Comment by klp2** [comment]
[PerlIO::gzip](https://metacpan.org/pod/PerlIO::gzip) and [IO::Uncompress::Gunzip](https://metacpan.org/pod/IO::Compress::Gzip) are two separate modules. If changing the `use` statement works, that is something of a lucky accident. Installing `PerlIO::gzip` should fix this for you.

**Comment by oschwald** [comment]
`IO::Uncompress::Gunzip` is in core though. It might be worth converting the script to use that.

**Comment by zzqzzqzzq** [comment]
FWIW, Using IO::Uncompress::Gunzip is a two line change...

```
# use PerlIO::gzip;
use IO::Uncompress::Gunzip;
```

Line 260: 

```
#            open my $gin,  '<:gzip', \$content  or die $!;
            my $gin = new IO::Uncompress::Gunzip( \$content ) or die $!;
```

"Works for me", and doesn't require me to build/bundle/install PerlIO::gzip on RHEL7.
