### ISSUE TITLE
Uses strnlen() but does not check for its availability in configuration stage

### ISSUE THREAD

**Issue by grumpybozo** [maxmind/geoipupdate-legacy#71]
Since strnlen() is still a youngster (2008 POSIX) it is not implemented in some operating systems which are in active use (MacOS X 10.6, Solaris 10, FreeBSD 8, etc.) so the recent addition of one use of it (bin/geoipupdate.c line 593) makes the current version of geoipupdate unbuildable on such systems. See bash or ghostscript for examples of how to deal with strlen() being unavailable.

**Comment by horgh** [comment]
Hi @grumpybozo. Thank you for reporting this! Good catch!

I think I'd opt to replace it as a solution. It would be good to stick to C99 where possible.
