### ISSUE TITLE
man warning

### ISSUE THREAD

**Issue by z0rc** [maxmind/geoipupdate-legacy#8]
Debian 7, amd64, man 2.6.2

While I was preparing personal deb package of geoipupdate I run lintian check upon package and it threw the following warning:
`W: geoipupdate: manpage-has-errors-from-man usr/share/man/man5/GeoIP.conf.5.gz 32: warning: macro `Bl' not defined`
I just removed that string and seems it's fine. No visual differences noticed.
More details about check are at http://lintian.debian.org/tags/manpage-has-errors-from-man.html

**Comment by oschwald** [comment]
This directive was removed. Thanks.
