### ISSUE TITLE
Tool does not download CSV version

### ISSUE THREAD

**Issue by fxfitz** [maxmind/geoipupdate-legacy#91]
Just started using the `geoipupdate` tool and realized that it does not download the CSV version of the tool, which is a non-starter for us.

How can I get an updated version of the CSV?

**Comment by oschwald** [comment]
As you noticed, this tool is only for the binary databases. For the CSVs, I would recommend a simple script using `curl`. The reason why this tool is specific to the binary databases is that it is designed to be used with our database libraries. With the CSVs, the deployment requirements are going to be very specific to how they are used. If you are a paying client, [support@maxmind.com](mailto:support@maxmind.com) would be happy to provide more assistance.

**Comment by fxfitz** [comment]
_Just_ saw the Readme!

> The GeoIP Update program performs automatic updates of GeoIP2 and GeoIP Legacy binary databases. CSV databases are not supported.

Okay, I'll contact them. Thanks!
