### ISSUE TITLE
Question About .dat File

### ISSUE THREAD

**Issue by fxfitz** [maxmind/geoipupdate-legacy#92]
Just a quick question about the .dat files that the updater downloaded...

Output:
```
MD5 Digest of installed database is 1e43a1a5c531cc8e11fb4f83a1c0ec7a
/usr/share/GeoIP/GeoLiteCountry.dat is up to date, no updates required
GeoIP Database up to date
MD5 Digest of installed database is 0637ec47d9b4d8107d32e94c35f7f311
/usr/share/GeoIP/GeoLiteCity.dat is up to date, no updates required
GeoIP Database up to date
```

The .dat file that was downloaded/updated... is that the same format as the "mmdb" file?

**Comment by oschwald** [comment]
No, the `dat` format is the legacy database format.

**Comment by fxfitz** [comment]
@oschwald Ah, ok. So does the `geoipupdate` utility fetch the mmdb format at all?

**Comment by oschwald** [comment]
Yes, it does. What edition IDs are specified in your `GeoIP.conf` file?

**Comment by fxfitz** [comment]
`ProductIds GeoIP2-Country`

**Comment by oschwald** [comment]
Based on the output above, it sounds like another `GeoIP.conf` file is being used. I'd suggest going to our website and starting a live chat. They should be able to help you figure out what is going on.

**Comment by fxfitz** [comment]
Hah! Yup! That was *totally* it.

Thanks for answering that question! I'm looking into why this is failing now, but I'll probably just ping support about it tomorrow.

```
$ sudo geoipupdate
/usr/share/GeoIP/GeoIP2-Country.mmdb can't be opened, proceeding to download database
Updating /usr/share/GeoIP/GeoIP2-Country.mmdb
Received Error -21 (Sanity check database_info string failed) when attempting to update GeoIP Database
```

**Comment by oschwald** [comment]
That error is from a 1.x version of `geoipupdate`, which doesn't support GeoIP2 databases. You will need to upgrade to a 2.x version.

**Comment by fxfitz** [comment]
Perfect! Thanks for the info!
